/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Brand green — from logo background
        primary: {
          50:  '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          950: '#052e16',
        },
        // Brand red — from logo text
        brand: {
          50:  '#fff1f0',
          100: '#ffe0dc',
          200: '#ffc5be',
          300: '#ff9a90',
          400: '#ff6b5e',
          500: '#e8321f',
          600: '#c62515',
          700: '#a71d0f',
          800: '#8a1c12',
          900: '#721d15',
          950: '#3e0905',
        },
        // Brand orange/amber — from logo leaves
        accent: {
          50:  '#fff8ed',
          100: '#ffefd3',
          200: '#ffd9a5',
          300: '#ffbc6d',
          400: '#ff9533',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
          950: '#431407',
        },
        // Gold leaf tip
        gold: {
          50:  '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        // Neutrals
        ink: {
          50:  '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        sans:    ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        script:  ['"Caveat Brush"', 'cursive'],
      },
      keyframes: {
        'fade-in':        { '0%': { opacity: '0' },                                        '100%': { opacity: '1' } },
        'fade-up':        { '0%': { opacity: '0', transform: 'translateY(24px)' },         '100%': { opacity: '1', transform: 'translateY(0)' } },
        'fade-down':      { '0%': { opacity: '0', transform: 'translateY(-24px)' },        '100%': { opacity: '1', transform: 'translateY(0)' } },
        'scale-in':       { '0%': { opacity: '0', transform: 'scale(0.92)' },              '100%': { opacity: '1', transform: 'scale(1)' } },
        'slide-in-right': { '0%': { opacity: '0', transform: 'translateX(40px)' },         '100%': { opacity: '1', transform: 'translateX(0)' } },
        'slide-in-left':  { '0%': { opacity: '0', transform: 'translateX(-40px)' },        '100%': { opacity: '1', transform: 'translateX(0)' } },
        'slide-up-fade':  { '0%': { opacity: '0', transform: 'translateY(60px) rotate(-15deg)' }, '100%': { opacity: '1', transform: 'translateY(0) rotate(0deg)' } },
        'float':          { '0%, 100%': { transform: 'translateY(0)' },                    '50%': { transform: 'translateY(-12px)' } },
        'float-slow':     { '0%, 100%': { transform: 'translateY(0) rotate(-4deg)' },      '50%': { transform: 'translateY(-18px) rotate(4deg)' } },
        'spin-slow':      { '0%': { transform: 'rotate(0deg)' },                           '100%': { transform: 'rotate(360deg)' } },
        'pulse-soft':     { '0%, 100%': { opacity: '1' },                                  '50%': { opacity: '0.45' } },
        'shimmer':        { '0%': { backgroundPosition: '-200% 0' },                       '100%': { backgroundPosition: '200% 0' } },
        'wiggle':         { '0%, 100%': { transform: 'rotate(-4deg)' },                    '50%': { transform: 'rotate(4deg)' } },
        'pop':            { '0%': { transform: 'scale(0.7)', opacity: '0' },               '60%': { transform: 'scale(1.08)' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'marquee':        { '0%': { transform: 'translateX(0)' },                          '100%': { transform: 'translateX(-50%)' } },
        'drift':          { '0%': { transform: 'translate(0,0) rotate(0deg)' },            '50%': { transform: 'translate(16px,-12px) rotate(6deg)' }, '100%': { transform: 'translate(0,0) rotate(0deg)' } },
        // Drumstick entry: sweeps in from bottom-right, rotating
        'drumstick-in': {
          '0%':   { opacity: '0', transform: 'translate(120px, 120px) rotate(60deg) scale(0.4)' },
          '60%':  { opacity: '1', transform: 'translate(-8px, -8px) rotate(-6deg) scale(1.05)' },
          '80%':  { transform: 'translate(4px, 4px) rotate(2deg) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translate(0, 0) rotate(0deg) scale(1)' },
        },
        // Steam wisps
        'steam': {
          '0%':   { opacity: '0', transform: 'translateY(0) scaleX(1)' },
          '30%':  { opacity: '0.7' },
          '100%': { opacity: '0', transform: 'translateY(-40px) scaleX(1.4)' },
        },
        // Logo pop-in
        'logo-in': {
          '0%':   { opacity: '0', transform: 'scale(0.6) translateY(20px)' },
          '70%':  { transform: 'scale(1.05) translateY(-4px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        // Sparkle
        'sparkle': {
          '0%, 100%': { opacity: '0', transform: 'scale(0)' },
          '50%':      { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'fade-in':        'fade-in 0.6s ease-out forwards',
        'fade-up':        'fade-up 0.7s ease-out forwards',
        'fade-down':      'fade-down 0.7s ease-out forwards',
        'scale-in':       'scale-in 0.5s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.6s ease-out forwards',
        'slide-in-left':  'slide-in-left 0.6s ease-out forwards',
        'slide-up-fade':  'slide-up-fade 0.8s cubic-bezier(0.22,1,0.36,1) forwards',
        'float':          'float 5s ease-in-out infinite',
        'float-slow':     'float-slow 7s ease-in-out infinite',
        'spin-slow':      'spin-slow 18s linear infinite',
        'pulse-soft':     'pulse-soft 2.5s ease-in-out infinite',
        'shimmer':        'shimmer 2.5s linear infinite',
        'wiggle':         'wiggle 0.7s ease-in-out infinite',
        'pop':            'pop 0.45s cubic-bezier(0.22,1,0.36,1) forwards',
        'marquee':        'marquee 30s linear infinite',
        'drift':          'drift 10s ease-in-out infinite',
        'drumstick-in':   'drumstick-in 1.1s cubic-bezier(0.22,1,0.36,1) forwards',
        'steam':          'steam 2s ease-in-out infinite',
        'logo-in':        'logo-in 0.8s cubic-bezier(0.22,1,0.36,1) forwards',
        'sparkle':        'sparkle 1.2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
